version: '3.9'
services:
  db:
    container_name: 'db'
    image: postgres
    env_file: .env
    ports:
      - 5434:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'db', '-p', '5432']
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 1s

  api:
    container_name: 'api'
    build: .
    env_file: .env
    tty: true
    ports:
      - 80:3001
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg-data:
