import { Entity, PrimaryGeneratedColumn, Column, OneToMany } from 'typeorm';
import { Task } from '../../tasks/entities/task.entity';
import { ApiProperty } from '@nestjs/swagger';
@Entity()
export class Project {
  @PrimaryGeneratedColumn('uuid')
  @ApiProperty({
    example: 'de8df8eb-58ea-4f8e-8cf4-d872819c4ec5',
    description: 'random UUID Generated by postgres',
  })
  id: string;

  @Column()
  @ApiProperty({
    example: 'Mordor Project',
    description: 'project name',
  })
  nome: string;

  @Column()
  @ApiProperty({
    example: 'the jouney to destroy the rin',
    description: 'simple description about the project',
  })
  descricao: string;

  @OneToMany((_type) => Task, (task) => task.project, {
    eager: true,
    cascade: true,
  })
  tasks: Task[];
}
